### ISSUE TITLE
Add the possibility to load sub-configurations from everywhere in the FS

### ISSUE THREAD

**Issue by matteogabburo** [matteogabburo/pyovra-git#15]
At the moment, pyovra is designed to load sub-configurations only from some directories (to force the programmer to organize the configurations into a hierarchical fashion). For example

```.yaml
program:
    dataset: §wikiqa.yaml
```
will load a configuration called ```wikiqa.yaml``` from the directory ```program/dataset```

### Request:
When we want to load a configuration file with the special symbol "§", we should be able to call the sub-configuration from everywhere in the filesystem. For example

```.yaml
program:
    dataset: §somewhere/in/the/FS/wikiqa.yaml
```

**Comment by lucadiliello** [comment]
Makes sense
