### ISSUE TITLE
Number in scientific notation parsed as strings

### ISSUE THREAD

**Issue by lucadiliello** [matteogabburo/pyovra-git#18]
When using YAML configurations, this `1.0e-06` is parsed as a float while this `1e-06` is parsed as a string.

**Comment by matteogabburo** [comment]
It is a known bug of PyYaml (mentioned here https://github.com/yaml/pyyaml/issues/173), I'm fixing the bug using ruamel.yaml instead of PyYaml to load .yaml files.
